---
name: Update submodules!

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  build:
    name: Update submodules
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'arichorn/uYouPlus'
      CHECKOUT_BRANCH: 'main'
      PR_AGAINST_BRANCH: 'main'
      OWNER: 'arichorn'

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3

      ####################################
      # Run the action against code base #
      ####################################
      - name: run action
        id: run_action
        run: |
          if ! [[ -z "${{ secrets.GO_TOKEN }}" ]]; then
             echo ::set-output has_token=true
          else
             echo ::set-output has_token=false
          fi

        uses: qnblackcat/github-action-create-pr-parent-submodule@main
        with:
          github_token: ${{ secrets.RELEASE_HUB_SECRET }}
          parent_repository: ${{ env.PARENT_REPOSITORY }}
          checkout_branch: ${{ env.CHECKOUT_BRANCH }}
          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
          owner: ${{ env.OWNER }}
